server:
  port: 8081

internal:
  secret: ${INTERNAL_SECRET:local-internal-secret}

spring:
  application:
    name: corebank-service
  datasource:
    url: ${CORE_DB_URL:jdbc:mysql://localhost:3306/core_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${CORE_DB_USERNAME:fix}
    password: ${CORE_DB_PASSWORD:fix}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration,classpath:db/seed

springdoc:
  api-docs:
    path: /v3/api-docs
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui/index.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
